---
title: "Early Prediction of PFS from Confirmed Response and Tumor Sizes"
author: "Karim Naguib"
format: html
---

```{r}
#| label: setup
#| include: false

library(magrittr)
library(tidyverse)
library(rlang)
library(cmdstanr)
library(loo)
library(posterior)
library(tidybayes)
library(bayesplot)
library(here)
library(targets)
library(colorspace)

# Using different temp directories on SCP and locally.
tmp_dir <- if (nchar(Sys.getenv("TMP")) > 0) file.path(Sys.getenv("TMPDIR"), "adc-early-predict") else here("temp")

knitr::opts_chunk$set(cache.path = file.path("/wscratch", Sys.getenv("USER"), "adc-early-predict/cache/"))

ggplot2::theme_set(theme_minimal(base_family = "Arial"))

source(here("r", "util.R"))
source(here("r", "crcr.R"))

tar_config_set(store = file.path(tmp_dir, "_targets"), script = here("_targets.R"))
```

# Data

```{r}
#| label: load-analysis-data
#| cache: true
#| cache-lazy: true

tar_load(c("treated_confirmed_resp_analysis_data", "treated_confirmed_resp_stan_data"))
```

```{r}
#| label: fig-confirmed-response-week
#| fig-width: 10

treated_confirmed_resp_analysis_data |> 
  ggplot(aes(confirmed_response_week)) +
  geom_bar(aes(fill = confirmed_response_censored), alpha = 0.75, position = "stack") +
  scale_x_continuous("Confirmed Response Week", breaks = (seq(0, 126, by = 12))) +
  scale_fill_discrete("Unclassified", type = AZ_palette) +
  facet_wrap(vars(trial), scales = "free_y") 
```

```{r}
#| label: fig-response-classification-time

tar_read("km_trial_confirmed_response") |>
  rowwise() |>
  transmute(
    trial,
    conf_resp_km = list( 
      set_names(conf_resp_km, c("s", "n", "c", "e")) |>
        as_tibble() |> 
        mutate(t = seq(0, n() - 1))
    )
  ) |> 
  ungroup() |> 
  unnest(conf_resp_km) |> 
  ggplot() +
  geom_step(aes(t, s, color = trial), direction = "vh") +
  scale_x_continuous("Confirmed Response Study Week", breaks = (seq(0, 126, by = 12))) +
  scale_color_discrete("", type = AZ_palette) +
  labs(title = "Study time to confirmed response classification", y = "Proportion Unclassified") +
  theme(legend.position = "inside", legend.position.inside = c(0.7, 0.7)) +
  NULL

tar_read("km_trial_confirmed_response") |> 
  rowwise() |>
  transmute(
    trial,
    conf_resp_km_calendar = list( 
      set_names(conf_resp_km_calendar, c("s", "n", "c", "e")) |>
        as_tibble() |> 
        mutate(t = seq(0, n() - 1))
    )
  ) |> 
  ungroup() |> 
  unnest(conf_resp_km_calendar) |> 
  ggplot() +
  geom_step(aes(t, s, color = trial), direction = "vh") +
  scale_x_continuous("Confirmed Response Calendar Week", breaks = (seq(0, 240, by = 12))) +
  scale_color_discrete("", type = AZ_palette) +
  labs(title = "Calendar time to confirmed response classification", y = "Proportion Unclassified") +
  theme(legend.position = "inside", legend.position.inside = c(0.7, 0.7)) +
  NULL
```

```{r}
#| label: fig-assessment-visits

treated_confirmed_resp_analysis_data |> 
  select(trial, n_tumors, t_measure) |> 
  unnest(t_measure) |> 
  unnest(t_measure) |> 
  mutate(epoch = if_else(t_measure <= 0, "pre-screening", "treatment") |> as_factor()) |> 
  ggplot(aes(t_measure)) +
  geom_bar(aes(fill = epoch), alpha = 0.5) +
  scale_fill_discrete("", labels = str_to_title, type = AZ_palette) +
  scale_x_continuous("Week", breaks = (seq(0, 126, by = 12))) +
  labs(y = "Count", title = "Number of visits every week") +
  facet_wrap(vars(trial), scales = "free_y") +
  theme(legend.position = "top", axis.text.x = element_text(size = 7)) +
  coord_cartesian(xlim = c(0, 120))
```

```{r}
#| label: fig-experiment-entry-cdf

# treated_confirmed_resp_analysis_data |> 
#   ggplot() +
#   geom_segment(aes(x = trtsdt, xend = trtedt, y = usubjid, yend = usubjid), alpha = 0.25) +
#   labs(title = "Patient treatment start/end timelines", x = "", y = "") +
#   facet_wrap(vars(trial), ncol = 1, scales = "free") +
#   theme(axis.text.y = element_blank(), panel.grid.major.y = element_blank()) +
#   NULL

treated_confirmed_resp_analysis_data |> 
  ggplot() +
  stat_ecdf(aes(x = experiment_start_week, color = trial)) +
  geom_vline(xintercept = c(12, 24, 48), linetype = "dotted") +
  scale_x_continuous("Experiment Entry Week") +
  labs(title = "Empirical CDF of experiment entry", y = "Proportion of Patients") +
  scale_color_discrete("", type = AZ_palette) +
  # facet_wrap(vars(trial), scales = "free") +
  theme(legend.position = "inside", legend.position.inside = c(0.7, 0.3)) +
  NULL
```

```{r}

recruit_res_list <- lst(
  prior = tar_read("prior_recruit_fit"),
  posterior = tar_read("recruit_fit")
) 

recruit_res_list |> 
  map_dfr(\(f) spread_rvars(f, lambda[trial]), .id = "fit_type") |> 
  ggplot() +
  stat_halfeye(aes(xdist = lambda, y = trial, color = fit_type, fill = fit_type, alpha = fit_type)) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.125, posterior = 0.25)) +
  labs(x = "Expected Experiment Entry Calendar Week", y = "") +
  guides(alpha = "none") +
  coord_cartesian(xlim = c(0, 100)) +
  theme(legend.position = "bottom") +
  NULL

recruit_res_list |> 
  map_dfr(\(f) spread_rvars(f, phi[trial]), .id = "fit_type") |> 
  ggplot() +
  stat_halfeye(aes(xdist = phi, y = trial, color = fit_type, fill = fit_type, alpha = fit_type)) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.125, posterior = 0.25)) +
  labs(x = "Dispersion", y = "") +
  guides(alpha = "none") +
  coord_cartesian(xlim = c(0, 25)) +
  theme(legend.position = "bottom") +
  NULL

recruit_res_list |> 
  map_dfr(\(f) spread_rvars(f, recruit_sd[trial]), .id = "fit_type") |> 
  ggplot() +
  stat_halfeye(aes(xdist = recruit_sd, y = trial, color = fit_type, fill = fit_type, alpha = fit_type)) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.125, posterior = 0.25)) +
  guides(alpha = "none") +
  coord_cartesian(xlim = c(0, 50)) +
  NULL
```
```{r}
ecdf_breaks <- 1:125

recruit_res_list |> 
  map_dfr(\(f) spread_rvars(f, sim_experiment_start_week[trial, i]), .id = "fit_type") |> 
  group_by(fit_type, trial) |> 
  reframe(t = ecdf_breaks, ecdf_rvar = rfun(\(w) ecdf(w)(ecdf_breaks))(sim_experiment_start_week)) |> 
  ggplot(aes(t)) +
  stat_ecdf(aes(x = experiment_start_week), linetype = "dashed", data = tar_read("treated_pfs_analysis_data")) +
  stat_lineribbon(aes(ydist = ecdf_rvar, color = fit_type, fill = fit_type, alpha = fit_type), .width = 0.8) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.125, posterior = 0.25)) +
  labs(x = "Calendar Week", y = "Proportion in Experiment") +
  guides(alpha = "none") +
  facet_wrap(vars(trial)) +
  theme(legend.position = "bottom")
```

```{r}
tar_load("recruit_maturity")

recruit_maturity |>
  filter(Pr(n_sample >= 10) >= 0.8) |> 
  ggplot() +
  # stat_lineribbon(aes(pred_week, ydist = n_sample), fill = alpha(AZ_platinum, 0.25), color = AZ_platinum, .width = 0.8) +
  stat_lineribbon(aes(pred_week, ydist = n_sample, fill = lambda, color = lambda, group = str_c(trial, lambda)), alpha = 0.25, .width = 0.8) +
  geom_hline(yintercept = 10, linetype = "dotted") +
  scale_x_continuous(breaks = seq(6, 48, 6)) +
  # facet_grid(vars(lambda), vars(trial), scales = "free_y") +
  labs(x = "Prediction Calendar Week", y = "Sample Size") +
  facet_grid(col = vars(trial), scales = "free_y") +
  NULL

recruit_maturity |> 
  filter(Pr(n_sample >= 10) >= 0.8) |> 
  ggplot() +
  # stat_lineribbon(aes(pred_week, ydist = maturity_rate), fill = alpha(AZ_platinum, 0.25), color = AZ_platinum, .width = 0.8) +
  stat_lineribbon(
    aes(pred_week, ydist = maturity_rate, fill = lambda, color = lambda, group = str_c(trial, lambda)), alpha = 0.25, .width = 0.8
  ) +
  scale_x_continuous(breaks = seq(6, 48, 6)) +
  labs(x = "Prediction Calendar Week", y = "Maturity Rate") +
  facet_grid(col = vars(trial), scales = "free_y") +
  # facet_grid(vars(lambda), vars(trial), scales = "free_y") +
  NULL
```


```{r}
#| label: fig-response-classification

treated_confirmed_resp_analysis_data |> 
  mutate(
    confirmed_response = factor(confirmed_response, levels = c(TRUE, FALSE), labels = c("Response", "Non-response")) |> 
      fct_explicit_na("Unclassified")
  ) |>  
  ggplot(aes(confirmed_response)) +
  geom_bar(alpha = 0.25) +
  labs(title = "Confirmed response counts", x = "", y = "Count") +
  facet_wrap(vars(trial), nrow = 1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#| label: fig-age-group

treated_confirmed_resp_analysis_data |> 
  ggplot() +
  geom_bar(aes(age_group), alpha = 0.25) +
  facet_wrap(vars(trial))
```

```{r}
#| label: fig-age-group

treated_confirmed_resp_analysis_data |> 
  ggplot() +
  geom_bar(aes(ecogbl), alpha = 0.25) +
  facet_wrap(vars(trial), nrow = 1)
```

```{r}
#| label: fig-hormon

treated_confirmed_resp_analysis_data |> 
  ggplot() +
  geom_bar(aes(hormonr), alpha = 0.25) +
  facet_wrap(vars(trial), nrow = 1)
```

```{r}
#| label: fig-prior-pertuzumab-treatment

treated_confirmed_resp_analysis_data |> 
  ggplot() +
  geom_bar(aes(prior_pertuzumab_treatment), alpha = 0.25) +
  facet_wrap(vars(trial), nrow = 1)
```

```{r}
#| label: fig-prior-cdk46-inhibit-treatment

treated_confirmed_resp_analysis_data |> 
  ggplot() +
  geom_bar(aes(prior_cdk46_inhibit_treatment), alpha = 0.25) +
  facet_wrap(vars(trial), nrow = 1)
```
```{r}
#| label: fig-her2-status

treated_confirmed_resp_analysis_data |> 
  ggplot() +
  geom_bar(aes(her2_status), alpha = 0.25) +
  facet_wrap(vars(trial))
```

```{r}
#| label: fig-history-visceral-disease

treated_confirmed_resp_analysis_data |> 
  ggplot() +
  geom_bar(aes(hist_visceral_disease), alpha = 0.25) +
  facet_wrap(vars(trial))
```

# Model

## Confirmed Response Competing Risks Model

First, we have a competing risks model of time-to-classification, with a separate hazard function per risk (confirmed response vs confirmed non-response).

$$
\lambda_r(t;\boldsymbol{x,\theta}_r) = \lambda_{rt}\exp(\boldsymbol{x\beta}_r),\,r \in \{\textrm{responder, non-responder}\} 
$$
The conditional probability of classification as a responder or non-responder (exiting the state of being unclassified) is

$$
\begin{align}
\Pr[Y_{rt} = 1 \mid Y_{r,t-1} = 0, \boldsymbol{x, \beta}_r] &= 1 - \exp[-\lambda_r(t;\boldsymbol{x,\beta}_r)] \\
\Pr[Y_{rt} = 1 \mid Y_{r,t-1} = 1, \boldsymbol{x, \beta}_r] &= 1 \\
\end{align}
$$

```{r}
#| label: conf-resp-hazard-ratio
#| cache: true

hb <- seq(0, 3, by = 0.1)

bind_rows(
  prior = tar_read("prior_crcr_hazard_ratio"),
  post = tar_read("crcr_hazard_ratio"),
  .id = "fit_type"
) |> 
  group_by(trial, k, fit_type) |> 
  reframe(t = hb[-1], bindist = rvar_sample_hist(patient_crcr_hazard_ratio, hb)) |> 
  mutate(k = factor(k, levels = 1:2, labels = c("Response", "Non-response"))) |> 
  ggplot(aes(t)) +
  stat_lineribbon(aes(ydist = bindist, color = fit_type, fill = fit_type, alpha = fit_type),
                  linewidth = 1,
                  step = "vh",
                  .width = c(0.5, 0.8)) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.05, post = 0.25)) +
  facet_grid(vars(trial), vars(k), scales = "free_y") +
  guides(alpha = "none") +
  NULL
```

```{r}

covar_param <- lst(prior = prior_confirmed_resp_comp_risk_res, post = confirmed_resp_comp_risk_res) |> 
  map_dfr(get_conf_resp_covar_param, .id = "fit_type") 

covar_param |> 
  mutate(k = factor(k, levels = 1:2, labels = c("Response", "Non-response"))) |> 
  ggplot() +
  stat_halfeye(aes(xdist = crcr_covar_effect, y = factor(covar), color = fit_type, fill = fit_type), alpha = 0.25, .width = 0.8) +
  scale_y_discrete("Parameter") +
  scale_color_discrete(type = AZ_palette, aesthetics = c("color", "fill")) +
  facet_grid(vars(k), vars(trial))
```

```{r}

tumor_param <- lst(prior = prior_confirmed_resp_comp_risk_res, post = confirmed_resp_comp_risk_res) |> 
  map_dfr(get_conf_resp_tumor_param, .id = "fit_type") 

tumor_param |> 
  mutate(k = factor(k, levels = 1:2, labels = c("Response", "Non-response"))) |> 
  ggplot() +
  stat_halfeye(aes(xdist = crcr_tumor_stim_pop_coef, y = factor(m), color = fit_type, fill = fit_type), alpha = 0.25, .width = 0.8) +
  scale_y_discrete("Parameter") +
  scale_color_discrete(type = AZ_palette, aesthetics = c("color", "fill")) +
  facet_grid(vars(k), vars(trial))
```


```{r}

conf_resp_cif <- lst(prior = prior_confirmed_resp_comp_risk_res, post = confirmed_resp_comp_risk_res) |> 
  map_dfr(get_conf_resp_cif, .id = "fit_type") 

conf_resp_prob_confirmed <- conf_resp_cif |> 
  group_by(fit_type, trial, i, k) |> 
  filter(min_rank(t) == n()) |> 
  group_by(fit_type, trial, i) |> 
  mutate(cif = cif / rvar_sum(cif)) |> 
  ungroup() |> 
  filter(k == 2)

conf_resp_cif |> 
  filter(trial == "Breast04", i <= 5) |>
  mutate(k = factor(k, levels = 1:2, labels = c("Response", "Non-response"))) |> 
  ggplot(aes(t)) +
  stat_lineribbon(aes(ydist = cif, color = fit_type, fill = fit_type), alpha = 0.25, linewidth = 2, .width = c(0.5, 0.8)) +
  scale_color_discrete(type = AZ_palette, aesthetics = c("color", "fill")) +
  facet_grid(vars(i), vars(k))
```

```{r}
conf_resp_prob <- lst(prior = prior_confirmed_resp_comp_risk_res, post = confirmed_resp_comp_risk_res) |> 
  map_dfr(get_conf_resp_prob, .id = "fit_type") 
```

```{r}
tar_load("confirmed_resp_pfs_res")

hb <- seq(0, 1, by = 0.05)

cif <- confirmed_resp_pfs_res$fit[[2]] |> 
  spread_rvars(cif[i, t, k])

cif2 <- xx |>  
  spread_rvars(cif[i, t, k])

cif2 |>
  mutate(fit_type = "posterior") |> 
  filter(t %in% seq(1, 100, 10)) |> 
  group_by(fit_type, t, k) |> 
  reframe(p = hb[-1], bindist = rvar_sample_hist(cif, hb)) |> 
  mutate(k = factor(k, levels = 1:2, labels = c("Non-response", "Response"))) |> 
  ggplot(aes(p)) +
  stat_lineribbon(aes(ydist = bindist, color = fit_type, fill = fit_type, alpha = fit_type),
                  linewidth = 1,
                  step = "vh",
                  .width = c(0.5, 0.8)) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.125, posterior = 0.25)) +
  # labs(x = "Hazard Ratio", y = "Density") +
  scale_y_continuous("", breaks = NULL) +
  facet_grid(vars(t), vars(k), scales = "free_y", switch = "y") +
  guides(alpha = "none") +
  theme(legend.position = "bottom", strip.text.y.left = element_text(angle = 0), strip.placement = "outside") +
  NULL
```

## PFS Model

```{r}
pfs_cr_median_pfs <- bind_rows(
  prior = tar_read("prior_conf_resp_median_pfs"), 
  posterior = tar_read("conf_resp_median_pfs"), 
  .id = "fit_type"
)  
```

```{r}
#| label: fig-median-pfs-conf-resp

pfs_cr_median_pfs |> 
  ggplot() +
  stat_halfeye(
    aes(xdist = sim_median_pfs, y = trial, color = fit_type, fill = fit_type, alpha = fit_type), 
    na.rm = TRUE, 
    # position = position_dodge(width = 0.5), 
    .width = c(0.5, 0.8)
  ) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.125, posterior = 0.25)) +
  labs(y = "", x = "Median PFS [Weeks]") +
  guides(alpha = "none") +
  theme(legend.position = "bottom")
  NULL
```

```{r}
#| label: fig-pfs-conf-resp-km

bind_rows(
  prior = tar_read("prior_conf_resp_km_est"), 
  posterior = tar_read("conf_resp_km_est"), 
  .id = "fit_type"
) |> 
  ggplot() +
  geom_step(
    aes(x = t, y = s, group = btype, linetype = "Observed Data"), 
    data = tar_read("km_res_calculated") |> filter(treated, fct_match(btype, "lb"))
  ) +
  stat_lineribbon(aes(x = t - 1, ydist = km_est, color = fit_type, fill = fit_type, alpha = fit_type), step = TRUE, .width = c(0.8)) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.0625, posterior = 0.25)) +
  scale_linetype_manual("", values = "dashed") +
  labs(x = "Week", y = "Survival Probability") +
  facet_wrap(vars(trial)) +
  guides(alpha = "none") + 
  theme(legend.position = "bottom")
```

```{r}
#| eval: false

bind_rows(
  prior = tar_read("prior_pfs_conf_resp_marginal_exit_prob"), 
  post = tar_read("pfs_conf_resp_marginal_exit_prob"), 
  .id = "fit_type"
) |>
  filter(i <= 3, t <= 5) |> 
  mutate(k = factor(k, levels = 1:2, labels = c("Response", "Non-response"))) |> 
  ggplot() +
  stat_halfeye(
    aes(xdist = marginal_exit_prob, y = t, color = fit_type, fill = fit_type), 
    alpha = 0.25, na.rm = TRUE, position = position_dodge(width = 0.5), .width = c(0.5, 0.8)
  ) +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  facet_grid(vars(trial, i), vars(k)) +
  coord_cartesian(xlim = c(0, 0.1))
```
```{r}
pfs_conf_resp_hazard_ratio <- bind_rows(
  prior = tar_read("prior_pfs_conf_resp_hazard_ratio"),
  posterior = tar_read("pfs_conf_resp_hazard_ratio"),
  .id = "fit_type"
)  
```


```{r}
#| label: fig-pfs-conf-resp-hazard-ratio
#| fig-width: 10
#| cache: true

hb <- seq(0, 3, by = 0.1)

pfs_conf_resp_hazard_ratio |> 
  group_by(trial, k, fit_type) |> 
  reframe(t = hb[-1], bindist = rvar_sample_hist(time_invariant_hazard_ratio, hb)) |> 
  mutate(k = factor(k, levels = 1:2, labels = c("Non-response", "Response"))) |> 
  ggplot(aes(t)) +
  stat_lineribbon(aes(ydist = bindist, color = fit_type, fill = fit_type, alpha = fit_type),
                  linewidth = 1,
                  step = "vh",
                  .width = c(0.5, 0.8)) +
  geom_vline(xintercept = 1, linetype = "dotted") +
  scale_color_discrete("", label = str_to_title, type = AZ_palette, aesthetic = c("color", "fill")) +
  scale_alpha_manual("", values = c(prior = 0.125, posterior = 0.25)) +
  labs(x = "Hazard Ratio", y = "Density") +
  facet_grid(vars(trial), vars(k), scales = "free_y", switch = "y") +
  guides(alpha = "none") +
  theme(legend.position = "bottom", strip.text.y.left = element_text(angle = 0), strip.placement = "outside") +
  NULL
```

```{r}
tar_load("pfs_conf_resp_bootstrap_median_pfs")
```

```{r}
#| label: fig-pfs-conf-resp-boostrap
#| fig-height: 5 
#| fig-width: 6

pfs_conf_resp_bootstrap_median_pfs |> 
  ggplot(aes(x = prediction_week)) +
  geom_lineribbon(
    aes(y = bootstrap_median_pfs, ymin = bootstrap_median_pfs.lower, ymax = bootstrap_median_pfs.upper, color = "Bootstrap", fill = "Bootstrap"),
    alpha = 0.25
  ) +
  stat_pointinterval(aes(ydist = sim_median_pfs, color = "Full Data"),
    .width = 0.8, size = 0.5,
    data = \(d) semi_join(pfs_cr_median_pfs, d, by = "trial") |> filter(fct_match(fit_type, "posterior")) |> mutate(prediction_week = 48)
  ) +
  scale_color_manual("", values = c(AZ_platinum, AZ_plum), aesthetics = c("color", "fill")) +
  scale_x_continuous("Prediction Week", breaks = seq(0, 48, 12)) +
  labs(y = "Median PFS [Weeks]") +
  facet_grid(
    col = vars(recruit_lambda), row = vars(trial), 
    scales = "free", space = "free_x"
    # labeller = labeller(prediction_week = \(w) str_c("Week ", w)) 
  ) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 7), strip.text.y.right = element_text(size = 6.5)) +
  NULL
```

```{r}
#| fig-height: 5 
#| fig-width: 6

pfs_conf_resp_bootstrap_median_pfs |> 
  ggplot(aes(x = prediction_week)) +
  geom_lineribbon(
    aes(y = n_bootstrap_sample, ymin = n_bootstrap_sample.lower, ymax = n_bootstrap_sample.upper),
    color = AZ_platinum, fill = AZ_platinum, alpha = 0.25
  ) +
  geom_hline(aes(yintercept = n), linetype = "dotted", data = count(treated_confirmed_resp_analysis_data, trial)) +
  scale_x_continuous("Prediction Week", breaks = seq(0, 48, 12)) +
  labs(y = "Subsample Size") +
  facet_grid(
    col = vars(recruit_lambda), row = vars(trial), 
    scales = "free", space = "free_x"
  ) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 7), strip.text.y.right = element_text(size = 6.5)) +
  NULL
```

```{r}
#| fig-height: 5 
#| fig-width: 6

pfs_conf_resp_bootstrap_median_pfs |> 
  ggplot(aes(x = prediction_week)) +
  geom_lineribbon(
    aes(y = bootstrap_maturity_rate, ymin = bootstrap_maturity_rate.lower, ymax = bootstrap_maturity_rate.upper),
    color = AZ_platinum, fill = AZ_platinum, alpha = 0.25
  ) +
  # geom_hline(aes(yintercept = m), linetype = "dotted", 
  #            data = treated_confirmed_resp_analysis_data |> group_by(trial) |> summarize(m = 1 - mean(confirmed_response_censored))) +
  scale_x_continuous("Prediction Week", breaks = seq(0, 48, 12)) +
  labs(y = "Subsample Data Maturity Rate") +
  facet_grid(
    col = vars(recruit_lambda), row = vars(trial), 
    scales = "free", space = "free_x"
  ) +
  theme(legend.position = "bottom", axis.text.x = element_text(size = 7), strip.text.y.right = element_text(size = 6.5)) +
  NULL
```