---
title: "Early Prediction of Breast Cancer Survival"
---

# Tumor Size

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(rlang)
library(cmdstanr)
library(posterior)
library(tidybayes)
library(bayesplot)
library(here)

options(mc.cores = 12)

ggplot2::theme_set(theme_minimal())

future::plan(future::multisession(workers = 12))
```

```{r}
#| label: sim-settings

n_patients <- 1000
max_pfs <- 20
```


```{r}
#| label: tumor

tumor_model <- cmdstan_model(here("src", "tumor.stan"))

test_data <- lst(
  fit_data = FALSE,
  gen_tumor_sizes = TRUE,
  n_patients,
  n_measures = 2,
  # n_patient_tumors = rep(5, n_patients),
  n_patient_tumors = 1 + rbinom(n_patients, 5, 0.4),
  tumor_size = array(dim = 0)
)

res <- tumor_model$sample(data = test_data)

res_rvar <- res |> 
  spread_rvars(rep_tumor_size[tumor_index, measure_index]) |> 
  ungroup() |> 
  pivot_wider(id_cols = tumor_index, names_from = measure_index, values_from = rep_tumor_size, names_prefix = "tumor_size_") |>
  mutate(patient_id = rep(seq(test_data$n_patients), test_data$n_patient_tumors))

res_rvar |> 
  pivot_longer(tumor_size_1:tumor_size_2, names_prefix = "tumor_size_", names_transform = as.integer, names_to = "measure_id", values_to = "tumor_size") |> 
  filter(tumor_index < 6) |> 
  # unnest_rvars() |> 
  # filter(.draw == 1) |> 
  ggplot(aes(measure_id)) +
  geom_line(aes(y = tumor_size, group = str_c(tumor_index, .draw)), alpha = 0.125, data = \(d) unnest_rvars(d) |> filter(.draw <= 100)) +
  # geom_point(aes(y = gen_tumor_size, color = factor(tumor_id)))
  stat_lineribbon(aes(ydist = tumor_size, group = tumor_index), alpha = 0.125) +
  coord_cartesian(ylim = c(0, 15)) +
  NULL

fake_tumor_data <- res_rvar |>
  unnest_rvars() |>
  ungroup() |> 
  filter(.draw == 1)

# fake_data_res <- test_data |> 
#   list_modify(
#     fit_data = TRUE,
#     gen_tumor_sizes = FALSE,
#     tumor_size = fake_data$gen_tumor_size
#   ) |> 
#   tumor_model$sample()
```

```{r}
#| label: pfs-model

pfs_model <- cmdstan_model(here("src", "pfs.stan"), compile_standalone = TRUE, force_recompile = TRUE)

pfs_test_data <- test_data |> 
  list_modify(
    gen_pfs = TRUE,
    max_pfs = max_pfs,
    tumor_size = select(fake_tumor_data, tumor_size_1:tumor_size_2),
    pfs = rep(max_pfs, test_data$n_patients),
    censored = rep(1, test_data$n_patients)
  )

pfs_res <- pfs_model$sample(data = pfs_test_data, refresh = 0)
```

```{r}
rep_pfs_rvar <- pfs_res |> 
  spread_rvars(rep_pfs[patient_index], rep_censored[patient_index])

rep_pfs_param_rvar <- pfs_res |> 
  spread_rvars(log_lambda_gp_alpha, log_lambda_gp_rho, log_lambda_gp_intercept, tumor_stim_intercept, tumor_stim_coef[t]) |> 
  pivot_wider(names_from = t, values_from = tumor_stim_coef, names_prefix = "tumor_stim_coef_") 

lambda_rvar <- pfs_res |> 
  spread_rvars(log_lambda[t], base_pf_prob[t]) |> 
  mutate(lambda = exp(log_lambda))

lambda_rvar |> 
  ggplot(aes(t)) +
  stat_lineribbon(aes(ydist = lambda), fill = "black", alpha = 0.5, .width = 0.8) +
  geom_line(aes(y = lambda, group = .draw), alpha = 0.25, data = \(d) unnest_rvars(d) |> filter(.draw <= 50)) 

lambda_rvar |> 
  ggplot(aes(t)) +
  stat_lineribbon(aes(ydist = base_pf_prob), fill = "black", alpha = 0.5, .width = 0.8) +
  geom_line(aes(y = base_pf_prob, group = .draw), alpha = 0.25, data = \(d) unnest_rvars(d) |> filter(.draw <= 50)) 

pfs_res |> 
  spread_rvars(disease_progress_prob[i]) |> 
  mutate(patient_index = rep(seq(test_data$n_patients), each = max_pfs), t = rep(seq(max_pfs), n_patients)) |> 
  filter(patient_index == 1) |> 
  ggplot(aes(t)) +
  stat_lineribbon(aes(ydist = disease_progress_prob), fill = "black", alpha = 0.5, .width = 0.8) +
  geom_line(aes(y = disease_progress_prob, group = .draw), alpha = 0.25, data = \(d) unnest_rvars(d) |> filter(.draw <= 20)) +
  coord_cartesian(ylim = c(0, 1)) +
  NULL
```

```{r}
#| fig-height: 10
#| eval: false

draw <- 3

fake_pfs_data <- rep_pfs_rvar |> 
  unnest_rvars() |> 
  filter(.draw == draw) |> 
  rename_with(\(col) str_remove(col, "rep_")) |> 
  mutate(censored = vctrs::vec_cast(censored, logical()))

fake_pfs_param_data <- rep_pfs_param_rvar |>  
  unnest_rvars() |> 
  filter(.draw == draw) |> 
  pivot_longer(!starts_with("."), names_to = "param", values_to = "true")
  
fake_pfs_fit <- pfs_test_data |> 
  list_modify(
    gen_pfs = FALSE,
    fit_data = TRUE,
    !!!select(fake_pfs_data, pfs, censored)
  ) |> 
  pfs_model$sample(refresh = 0, init = \(chain_id) lst(tumor_stim_intercept = 0.01, tumor_stim_coef = c(0.01, 0.01)))

fake_pfs_fit_param_rvar <- fake_pfs_fit |> 
  spread_rvars(log_lambda_gp_alpha, log_lambda_gp_rho, log_lambda_gp_intercept, tumor_stim_intercept, tumor_stim_coef[t]) |> 
  pivot_wider(names_from = t, values_from = tumor_stim_coef, names_prefix = "tumor_stim_coef_") |> 
  pivot_longer(everything(), names_to = "param", values_to = "est")

bind_rows(
  prior = rep_pfs_param_rvar |> pivot_longer(everything(), names_to = "param", values_to = "est"),
  post = fake_pfs_fit_param_rvar,
  .id = "type"
) |> 
  ggplot(aes(y = param)) +
  stat_pointinterval(aes(xdist = est, color = type), size = 0.25, .width = 0.8, position = "dodge") +
  geom_vline(aes(xintercept = true), data = fake_pfs_param_data) +
  facet_wrap(vars(param), ncol = 1, scales = "free") +
  theme(axis.text.y = element_blank())
```

```{r}
#| label: fake-pfs-data
#| include: false
#| cache: true

# log_lambda <- pfs_model$functions$calc_gp_pred(seq(max_pfs), intercept = -2.0, alpha = 0.3, rho = 1.5, delta = 1e-9, eta = rnorm(max_pfs))

log_lambda <- c(-2.48777760709026, -2.57152726838213, -2.23380584287276, -1.90739893145911, -1.86259266390287, -1.92891255821976, -1.93801857664684, -1.78872336415524, -1.54522270753866, -1.48718504020436, -1.70706597143648, -1.82018710107277, -1.67764635563667, -1.69933003110133, -1.86937604603516, -2.03108481232034, -2.15728306810556, -2.11459406967666, -2.02311574428507, -2.08871876979315) 

gen_patient_interval_properties <- function(fake_tumor_data, log_lambda) {
  fake_tumor_data |> 
    group_by(patient_id) |>
    summarize(tumor_covar = list(cbind(tumor_size_1, tumor_size_2))) |>
    rowwise() |> 
    reframe(
      patient_id, 
      progress_prob = pfs_model$functions$calculate_progress_linear_prob(log_lambda, 0.2, c(0.15, 0.05), tumor_covar),
      hazard = pfs_model$functions$calculate_linear_hazard(log_lambda, 0.2, c(0.15, 0.05), tumor_covar),
      # progress_prob = pfs_model$functions$calculate_progress_linear_prob(log_lambda, 0.2, c(0.15, 0.0), tumor_covar),
      # hazard = pfs_model$functions$calculate_linear_hazard(log_lambda, 0.2, c(0.15, 0.0), tumor_covar),
      survival = cumprod(progress_prob)
    )  
}

gen_fake_pfs_data <- function(patient_interval_data) { 
  patient_interval_data |> 
    group_by(patient_id) |> 
    summarize(pfs = pfs_model$functions$pfs_rng(progress_prob)) |> 
    mutate(censored = pfs >= length(log_lambda))
}

patient_interval_data <- gen_patient_interval_properties(fake_tumor_data, log_lambda)

fake_data_sim <- tibble(sim_id = 1:100) |> 
  rowwise() |> 
  mutate(sim_data = list(gen_fake_pfs_data(patient_interval_data))) |> 
  ungroup() |> 
  mutate(
    sim_fit = furrr::future_map(.progress = TRUE, .options = furrr::furrr_options(seed = TRUE),
    # sim_fit = map(
      sim_data, 
      function(d) { 
        pfs_test_data |> 
          list_modify(
            gen_pfs = FALSE,
            fit_data = TRUE,
            pfs = d$pfs, censored = d$censored
          ) |> 
          pfs_model$sample(
            refresh = 0, 
            parallel_chains = 4, 
            init = \(chain_id) lst(tumor_stim_intercept = truncnorm::rtruncnorm(1, 0, mean = 0.01, sd = 0.05),
                                   tumor_stim_coef = c(truncnorm::rtruncnorm(1, 0, mean = 0.01, sd = 0.1),
                                                       truncnorm::rtruncnorm(1, 0, mean = 0.005, sd = 0.01)))
          )
      }
    ),
    
    sim_param_post = map(
      sim_fit, 
      \(f) spread_rvars(f, log_lambda_gp_alpha, log_lambda_gp_rho, log_lambda_gp_intercept, tumor_stim_intercept, tumor_stim_coef[t]) |>
        pivot_wider(names_from = t, values_from = tumor_stim_coef, names_prefix = "tumor_stim_coef_")
    ),
    
    sim_log_lambda_post = map(sim_fit, \(f) spread_rvars(f, log_lambda[m]))
  ) 
```

```{r}
fake_data_sim |> 
  select(!c(sim_data, sim_fit, sim_log_lambda_post)) |>
  unnest(sim_param_post) |> 
  add_row(sim_id = 0, rep_pfs_param_rvar) |>
  pivot_longer(!sim_id, names_to = "param", values_to = "est") |>
  mutate(est_type = if_else(sim_id > 0, "post", "prior")) |> 
  ggplot(aes(sim_id)) + 
  geom_hline(aes(yintercept = true_val), data = tribble(~ param,                   ~ true_val,
                                                        "log_lambda_gp_intercept", -2.0,
                                                        "log_lambda_gp_alpha",     0.3,
                                                        "log_lambda_gp_rho",       1.5,
                                                        "tumor_stim_intercept",    0.2,
                                                        "tumor_stim_coef_1",       0.15,
                                                        "tumor_stim_coef_2",       0.05)) +
  stat_pointinterval(aes(ydist = est, color = est_type), size = 0.25, .width = 0.8, fatten_point = 0) +
  facet_wrap(vars(param), scales = "free_y") +
  theme(axis.text.x = element_blank(), legend.position = "none")
```

```{r}
fake_data_sim |> 
  select(!c(sim_data, sim_fit, sim_param_post)) |>
  unnest(sim_log_lambda_post) |> 
  bind_rows(transmute(lambda_rvar, m = t, log_lambda, sim_id = 0)) |> 
  mutate(est_type = if_else(sim_id > 0, "post", "prior")) |> 
  ggplot(aes(sim_id)) + 
  geom_hline(aes(yintercept = true_val), data = tibble(m = 1:20, true_val = log_lambda)) +
  stat_pointinterval(aes(ydist = log_lambda, color = est_type), size = 0.5, .width = 0.8, fatten_point = 0) +
  facet_wrap(vars(m)) +
  theme(axis.text.x = element_blank(), legend.position = "none")
```